Implement the commerce settings connect URL method
facebookincubator/facebook-for-woocommerce pull request #1546
Opened 2020-09-15 21:25 UTC by ChaseWiseman

# Summary

Builds the Commerce connect URL.

### Story: [CH 63623](https://app.clubhouse.io/skyverge/story/63623)
### Release: #1477 

## UI Changes

_N/A_

## QA

- `integration Admin/Settings_Screens` tests pass

We will confirm further with acceptance tests once the settings screen has been implemented.

## Before merge

- [ ] I have confirmed these changes in each supported minor WooCommerce version

2020-09-15 23:58 UTC, wvega requested changes
Looks good @ChaseWiseman. Only one change request before we merge:

2020-09-15 23:58 UTC, wvega commented on includes/Admin/Settings_Screens/Commerce.php
> +		$redirect_url = add_query_arg( 'site_url', $site_url, facebook_for_woocommerce()->get_connection_handler()->get_proxy_url() );
I think we should encode `$site_url` as well:

````suggestion
		$redirect_url = add_query_arg( 'site_url', urlencode( $site_url ), facebook_for_woocommerce()->get_connection_handler()->get_proxy_url() );
```

2020-09-15 23:58 UTC, wvega commented on tests/integration/Admin/Settings_Screens/CommerceTest.php
> + * Tests the Admin\Settings class.
```suggestion
 * Tests the Settings_Screens\Commerce class.
```

2020-09-15 23:58 UTC, wvega commented on tests/integration/Admin/Settings_Screens/CommerceTest.php
> +		$this->assertStringContainsString( 'wc-api%3D' . \SkyVerge\WooCommerce\Facebook\Handlers\Connection::ACTION_CONNECT_COMMERCE . '%26nonce%3D', $connect_url );
If we choose to encode `$site_url` as well:

```suggestion
		$this->assertStringContainsString( 'wc-api%253D' . \SkyVerge\WooCommerce\Facebook\Handlers\Connection::ACTION_CONNECT_COMMERCE . '%2526nonce%253D', $connect_url );
```

2020-09-16 17:04 UTC, ChaseWiseman commented
@wvega makes sense! thanks for the suggestions. applying and merging 👍

2020-09-16 17:07 UTC, merged