Update product-categories.js to show the Edit Category modal
facebookincubator/facebook-for-woocommerce pull request #1570
Opened 2020-09-18 23:02 UTC by deivamagalhaes

# Summary

This PRs adds the JS used to show a modal if the Google product category ID is changed for an existing product category.

### Story: [CH 63678](https://app.clubhouse.io/skyverge/story/63678/update-product-categories-js-to-show-the-add-edit-category-modal)
### Release: #1477 

## Details

The JS here was "inspired" by the one used for the Settings modal. I've opted for creating new methods for the message and buttons because it seems the message for the Settings screen was updated on the pitch, so I'm guessing we may want to change that one separately in the near future.

## UI Changes

A modal is shown if the Google product category ID is changed for an existing product category: https://cloud.skyver.ge/6que6PK6

## QA

### Setup

1. Add `add_filter( 'wc_facebook_commerce_is_available', '__return_true' )`
1. Add `add_filter( 'wc_facebook_commerce_is_connected', '__return_true' )`

### Steps

1. Go to Products > Categories
1. Add a new category, selecting a Google product category for it
1. Click "Add new category"
    - [ ] The modal is not displayed
    - [ ] The category is saved (the Google product category ID is not saving, but this is not related to this PR)
1. Edit the existing category
1. Select a Google product category for it
1. Click "Update"
    - [ ] The modal is displayed
1. Click "Cancel"
    - [ ] The form is _not_ submitted
1. Click "Update" again
    - [ ] The modal is displayed
1. Click "Update default Google product category"
    - [ ] The form is submitted

## Before merge

- [ ] I have confirmed these changes in each supported minor WooCommerce version

2020-09-19 00:03 UTC, wvega requested changes
@deivamagalhaes looks good and the modal shows up as expected. I left a suggestion to remove a parameter I think we don't need and also have a question:

Should we set a specific width for the select fields?

This is how it looks on:

- Edit Category page with some categories already selected: https://cloud.skyver.ge/P8ubLyn2
- Edit Category page with no categories selected: https://cloud.skyver.ge/xQuLyYPl
- Add Category form: https://cloud.skyver.ge/yAubdZG4

I was going to suggest updating the field JS to set the width, but I think each screen where we show the field is going to use something different. It is `400px` on the Commerce settings (already set by WooCommerce's CSS), the text area in the Add/Edit Category forms use `95%` and it could be different on the Product tabs.

2020-09-21 20:20 UTC, deivamagalhaes commented on includes/Admin/Product_Categories.php
> +	 * @param string $taxonomy current taxonomy slug
Updated in https://github.com/facebookincubator/facebook-for-woocommerce/pull/1570/commits/f84f8a0563be6147d94561dc3e637bbf6d29423e.

2020-09-21 20:20 UTC, deivamagalhaes commented on includes/Admin/Product_Categories.php
> +	public function render_add_google_product_category_field( $taxonomy ) {
Updated in https://github.com/facebookincubator/facebook-for-woocommerce/pull/1570/commits/f84f8a0563be6147d94561dc3e637bbf6d29423e.

2020-09-22 01:27 UTC, wvega approved these changes
Thank you for the updates @deivamagalhaes. LGTM!

2020-09-22 01:27 UTC, merged