CAPI and Pixel improvements
facebookincubator/facebook-for-woocommerce pull request #1577
Opened 2020-09-21 19:44 UTC by josejia

The following improvements were done for Conversions API(CAPI) and Pixel events:

1. Addition of advanced matching information(first name, last name, email, phone number, city, state, country and zip code) in all pixel and CAPI events, extracted from Wordpress database
2. Addition of advanced matching information in Purchase CAPI events, extracted from order data.
3. Fetching automatic advanced matching settings for the installed pixel, to filter information from points 1 and 2.
4. Tagging of pixel events with WooCommerce agent string before they are sent.
5. Fixing content field in ViewContent events, it was send as an object instead of an array.

2020-09-22 18:06 UTC, wvega requested changes
@josejia the improvements are working for me! I was able to see PII data on browser and server events and the plugin honored my Advanced Matching settings.

Tests also passed.

I left several suggestions below and a couple of comments/questions. The main one is about using a transient to store the advanced matching settings to avoid issuing a GET request on every visit.

In addition to those, could you please update the modifications to use `tabs` for indentation (I saw a mix of spaces and tabs) to make them consistent with the rest of the plugin's code and the [WordPress PHP Coding Standards](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/) that we tried to follow with the changes added in the most recent versions?

Thanks.

2020-09-22 23:05 UTC, josejia commented on includes/fbutils.php
> +	}
Sure, thank you for the guidance, I didn't know where to include the classes.

2020-09-23 02:43 UTC, josejia commented on includes/Events/AAMSettings.php
> +		$response = wp_remote_get($url);
I added the load_aam_settings_of_pixel() method in facebook-commerce.php to cache the aam settings in a transient object, with the key wc_facebook_aam_settings. It is refreshed every 20 minutes.

2020-09-23 21:21 UTC, wvega reviewed
@josejia thank you for the updates! Tests continue to pass and settings are being retrieved less frequently now.

I terms of features I think we can merge. Both browser and server events include the new data where appropriate for me.

I think we can include these changes in version `2.0.2` of the plugin. That one is being being prepared on https://github.com/facebookincubator/facebook-for-woocommerce/pull/1467.

Can you please add docblocks with `@since` tags set to `2.0.2-dev.1` to the new methods and classes?

Once we are done with that, we can change the base branch to `release-2.0.2`. I can then fix the version and changelog conflicts that will likely show up and merge into the release branch.

Thanks.

2020-09-23 21:21 UTC, wvega commented on facebook-commerce-events-tracker.php
> +		 * @return array
We should add since tags to the new methods and classes:

```suggestion
		 * @since 2.0.2-dev.1
		 *
		 * @return array
```

2020-09-25 21:49 UTC, wvega approved these changes
@josejia looks good. Thank you for the latest modifications!

2020-10-02 22:42 UTC, merged