Enable connecting existing Commerce Accounts
facebookincubator/facebook-for-woocommerce pull request #1709
Opened 2020-11-20 23:46 UTC by denniskwon

2020-12-11 23:40 UTC, wvega requested changes
@denniskwon if I understand correctly, the purpose of this PR is to:

- Show extra information about the Commerce connection in Instagram Checkout tab
- Bypass the connection onboarding if we already have a Commerce Manager ID from the page settings

My Facebook account is not setup to test the Commerce flow, but through code review and some mock tests I think the changes here achieve the items above.

I left some questions and suggestions below:

2020-12-11 23:44 UTC, wvega commented
I'm going to cherry pick the commits from this PR and from https://github.com/facebookincubator/facebook-for-woocommerce/pull/1727#pullrequestreview-550646960 to generate a test zip file.

We should probably rebase your commits on this branch on top of the most recent `release/instagram-checkout`. I rebased `release/instagram-checkout` some time ago and now this PR shows commits that are already there, but with a different changes.

2020-12-12 04:32 UTC, denniskwon commented on includes/Admin/Settings_Screens/Commerce.php
> +		<table class="form-table">
I believe the first conditional in the render method would take care of this, no?

2020-12-14 15:33 UTC, wvega commented on includes/Admin/Settings_Screens/Commerce.php
> +		<table class="form-table">
I meant to render the table inside this if statement:

https://github.com/facebookincubator/facebook-for-woocommerce/blob/c7b3dbd2ee2b426d53a91d3f64785aa2ea5e6c8c/includes/Admin/Settings_Screens/Commerce.php#L289

I believe it's possible for users to be connected to Facebook and not have a Commerce connection yet, for example if they upgraded from a version that didn't request the page access token.

2021-01-27 02:42 UTC, merged