Fix product set
facebookincubator/facebook-for-woocommerce pull request #1776
Opened 2021-02-17 20:41 UTC by sc-ecolasurdo

- Bug fixed when Product Set is empty.
- Change the version used for Product Set deletion.
- Implement a filter to send the _allow_live_product_set_deletion_ parameter in _true_ by default in Product Set deletion process.
Reference: [Facebook Documentation](https://developers.facebook.com/docs/marketing-api/reference/product-set#Deleting)

2021-02-17 22:42 UTC, jconroy commented
Thanks @sc-ecolasurdo !

2021-02-17 23:02 UTC, msaggiorato requested changes

2021-02-17 23:02 UTC, msaggiorato commented on includes/fbgraph.php
> +			$params = ( true === apply_filters( 'wc_facebook_commerce_allow_live_product_set_deletion', $product_set_id ) ) ? '?allow_live_product_set_deletion=true' : '';
Hey @sc-ecolasurdo , shouldn't the filter be like this? This way we default it to true, and avoid the need for a `__return_true` filter at the top.

```suggestion
			$params = ( true === apply_filters( 'wc_facebook_commerce_allow_live_product_set_deletion', true, $product_set_id ) ) ? '?allow_live_product_set_deletion=true' : '';
```

2021-02-18 18:35 UTC, msaggiorato approved these changes

2021-02-19 04:41 UTC, jconroy commented
I've created a release branch https://github.com/facebookincubator/facebook-for-woocommerce/pull/1779

2021-02-19 05:05 UTC, jconroy approved these changes
This appears to be testing well for me.  Confirm product set is removed from FB if it becomes empty (I had a product set/category with a single item and removed that item from the category - confirmed on the FB end in my catalog)

Just had a suggestion for rewording one of the inline comments.

Can you re target the 2.3.1 branch and also entries to the readme and changelog in this PR

Cheers!

2021-02-22 06:02 UTC, jconroy commented
> Can you re target the 2.3.1 branch and also entries to the readme and changelog in this PR

I've gone and done that for you

2021-02-22 06:20 UTC, merged